#pragma once

#include "C:\Factory\Common\all.h"
#include "C:\Factory\Common\Options\Prime.h"
#include "C:\Factory\Common\Options\Prime2.h"
#include "C:\Factory\Common\Options\Prime3.h"
#include "C:\Factory\Common\Options\uintx\uint64.h"
#include "C:\Factory\Common\Options\uintx\uint128.h"
#include "C:\Factory\Common\Options\uintx\uint256.h"
#include "C:\Factory\Common\Options\uintx\uint512.h"
#include "C:\Factory\Common\Options\uintx\uint1024.h"
#include "C:\Factory\Common\Options\uintx\uint4096.h"
#include "C:\Factory\Common\Options\uintx\uint8192.h"

#include "Consts.h"
#include "Config.h"
#include "Common.h"
#include "Stop.h"
#include "AToUI4096.h"
#include "IsPrime.h"
#include "Factorization.h"
#include "FindPrimes.h"
